production:
  feedly:
    url: "https://feedly.com"
    client_id: ""
    client_secret: ""
    access_token: ""
  instapaper:
    username: ""
    password: ""
    token: ""
    token_secret: ""
sandbox:
  feedly:
    url: "https://sandbox7.feedly.com"
    client_id: ""
    client_secret: ""
    access_token: ""